version: "3.0"

services:

  www:
    build:
      context: ../..
    image: moleculer-blog
    env_file: env
    environment:
      NODEID: "node-www"
      SERVICES: www
      PORT: 4000
    links:
      - nats
      - redis
    depends_on:
      - nats
      - redis
    labels:
      - "traefik.enable=true"   
      - "traefik.backend=www"
      - "traefik.port=4000"
      - "traefik.frontend.entryPoints=http"
      - "traefik.frontend.rule=PathPrefix:/"

  posts:
    build:
      context: ../..
    image: moleculer-blog
    env_file: env
    environment:
      NODEID: "node-posts"
      SERVICES: posts
    links:
      - nats
      - redis
      - mongo
    depends_on:
      - nats
      - redis
      - mongo

  users:
    build:
      context: ../..
    image: moleculer-blog
    env_file: env
    environment:
      NODEID: "node-users"
      SERVICES: users
    links:
      - nats
      - redis
      - mongo
    depends_on:
      - nats
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  likes:
    build:
      context: ../..
    image: moleculer-blog
    env_file: env
    environment:
      NODEID: "node-likes"
      SERVICES: likes
    links:
      - nats
      - redis
      - mongo
    depends_on:
      - nats
      - redis
      - mongo
    #deploy:
    #  replicas: 2

  # comments:
  #   build:
  #     context: ../..
  #   image: moleculer-blog
  #   env_file: env
  #   environment:
  #     NODEID: "node-comments"
  #     SERVICES: comments
  #   links:
  #     - nats
  #     - redis
  #     - mongo
  #   depends_on:
  #     - nats
  #     - redis
  #     - mongo

  nats:
    image: nats

  redis:
    image: redis:alpine

  mongo:
    image: mongo
    # volumes:
    #   - ../../db:/data/db

  traefik:
    image: traefik:1.7
    command: --web --docker --docker.domain=docker.localhost --logLevel=INFO --docker.exposedbydefault=false
    ports:
      - "3000:80"
      - "3001:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
